### ISSUE TITLE
Issues with psycopg2-binary: libpq not found

### ISSUE THREAD

**Issue by frafra** [ClericPy/zipapps#8]
```
# python3 -m zipapps -c -a conf-template.yml -a manager.py -o manager.pyz -m manager:app -u AUTO -r requirements.txt 
[...]
[INFO]: these names will be unzipped while running: yaml,psycopg2,_ldap.cpython-38-x86_64-linux-gnu.so
[INFO] Temp cache has been cleaned. (<TemporaryDirectory '/tmp/tmpflsdglju'>)
========== Successfully built `manager.pyz` ==========
# python3 manager.pyz
Traceback (most recent call last):
  File "/usr/lib64/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib64/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "manager.pyz/__main__.py", line 94, in <module>
  File "manager.pyz/__main__.py", line 62, in main
  File "<frozen zipimport>", line 259, in load_module
  File "/app/manager.pyz/manager.py", line 7, in <module>
  File "<frozen zipimport>", line 259, in load_module
  File "/app/manager.pyz/ldap2pg/__init__.py", line 1, in <module>
  File "<frozen zipimport>", line 259, in load_module
  File "/app/manager.pyz/ldap2pg/config.py", line 22, in <module>
  File "/app/zipapps_cache/manager/psycopg2/__init__.py", line 51, in <module>
    from psycopg2._psycopg import (                     # noqa
ImportError: libpq-6f24e430.so.5.13: cannot open shared object file: No such file or directory
```

**Comment by ClericPy** [comment]
this file name is not `*.so` as I can see, so try using ` -u="*"` instead of ` -u AUTO` to unzip all libs

**Comment by ClericPy** [comment]
And please let me known if that works or not.

**Comment by frafra** [comment]
Thanks; it got included. I hit another error, but I will open a new issue.
