### ISSUE TITLE
pkg_resources.DistributionNotFound: The 'ldap2pg' distribution was not found and is required by the application

### ISSUE THREAD

**Issue by frafra** [ClericPy/zipapps#9]
It seems that ldap2pg has not been included:

```
# grep -r ldap2pg requirements.txt 
ldap2pg==5.6 \
# python3 -m zipapps -c -a conf-template.yml -a manager.py -o manager.pyz -m manager:app -u '*' -r requirements.txt 
========== Start building `manager.pyz` with zipapps version <2021.04.29> ==========
[INFO]: the arg `unzip_path` has been changed to `zipapps_cache` by default.
[INFO]: output path is `manager.pyz`, you can reset it with the arg `output`.
Collecting click==8.0.1
  Using cached click-8.0.1-py3-none-any.whl (97 kB)
Collecting ldap2pg==5.6
  Using cached ldap2pg-5.6-py2.py3-none-any.whl (45 kB)
Collecting psycopg2-binary==2.9.1
  Using cached psycopg2_binary-2.9.1-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (3.4 MB)
Collecting pyasn1==0.4.8
  Using cached pyasn1-0.4.8-py2.py3-none-any.whl (77 kB)
Collecting pyasn1-modules==0.2.8
  Using cached pyasn1_modules-0.2.8-py2.py3-none-any.whl (155 kB)
Collecting python-ldap==3.3.1
  Using cached python-ldap-3.3.1.tar.gz (379 kB)
Collecting pyyaml==5.4.1
  Using cached PyYAML-5.4.1-cp38-cp38-manylinux1_x86_64.whl (662 kB)
Collecting typer==0.4.0
  Using cached typer-0.4.0-py3-none-any.whl (27 kB)
Building wheels for collected packages: python-ldap
  Building wheel for python-ldap (setup.py) ... done
  Created wheel for python-ldap: filename=python_ldap-3.3.1-cp38-cp38-linux_x86_64.whl size=342147 sha256=47ad3a2f7238615aedfda76e8b1987a97f4747790ee8ec43f954ec88324d0d04
  Stored in directory: /root/.cache/pip/wheels/db/e9/83/84ab9509d4cba1c1f74e929ffa8890184c23b95cbcc5d0b0a9
Successfully built python-ldap
Installing collected packages: pyasn1, pyasn1-modules, pyyaml, python-ldap, click, typer, psycopg2-binary, ldap2pg
Successfully installed click-8.0.1 ldap2pg-5.6 psycopg2-binary-2.9.1 pyasn1-0.4.8 pyasn1-modules-0.2.8 python-ldap-3.3.1 pyyaml-5.4.1 typer-0.4.0
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
[WARN]: .pyd/.so files may be imported incorrectly, set `--unzip=psycopg2,_ldap.cpython-38-x86_64-linux-gnu.so,yaml` or `--unzip=AUTO` to fix it. {'psycopg2': {'.so': 1}, '_ldap.cpython-38-x86_64-linux-gnu.so': {'.so': 1}, 'yaml': {'.so': 1}}
[INFO]: these names will be unzipped while running: *
[INFO] Temp cache has been cleaned. (<TemporaryDirectory '/tmp/tmpzzg5v6jn'>)
========== Successfully built `manager.pyz` ==========
[root@e18ad3fcfb4e app]# python3 manager.pyz 
Traceback (most recent call last):
  File "/usr/lib64/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib64/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "manager.pyz/__main__.py", line 94, in <module>
    main()
  File "manager.pyz/__main__.py", line 62, in main
    import manager
  File "/app/zipapps_cache/manager/manager.py", line 7, in <module>
    import ldap2pg
  File "/app/zipapps_cache/manager/ldap2pg/__init__.py", line 1, in <module>
    from .config import __version__, __dist__
  File "/app/zipapps_cache/manager/ldap2pg/config.py", line 40, in <module>
    __dist__ = get_distribution('ldap2pg')
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 481, in get_distribution
    dist = get_provider(dist)
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 357, in get_provider
    return working_set.find(moduleOrReq) or require(str(moduleOrReq))[0]
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 900, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 786, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'ldap2pg' distribution was not found and is required by the application
```

**Comment by ClericPy** [comment]
1. `-a` arg should use `path1,path2` instead of `-a path1 -a path2` so that the file `conf-template.yml` will be add to zip file.
2. try  `-u=*` or upgrade zipapps with `pip install -U zipapps --user`, there may be an import bug before.
